/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;

import com.google.gson.JsonArray;
import com.google.gson.JsonObject;

import java.util.Map;
import java.util.HashMap;

import serpapi.SerpApi;
import serpapi.SerpApiException;

public class App {
    public static void main(String[] args) {
        String apiKey = System.getenv("SERPAPI_KEY");
        if (apiKey == null || apiKey.isEmpty()) {
            System.out.println("Set environment variable SERPAPI_KEY or pass your key as the only argument.");
            System.exit(1);
        } 

        // set search location
        String location = "Austin,Texas";
        String engine = "google";
        System.out.println("find the first coffee shop in " + location + " using " + engine);

        Map<String, String> auth = new HashMap<>();
        auth.put("engine", engine);
        auth.put("api_key", apiKey);

        // create client
        SerpApi serpapi= new SerpApi(auth);

        // create search parameters
        Map<String, String> parameter = new HashMap<>();
        parameter.put("q", "Coffee");
        parameter.put("location", location);

        // perform search
        try {
            // get search results
            JsonObject data = serpapi.search(parameter);
            JsonArray organic = data.getAsJsonArray("organic_results");
            JsonObject first = organic.get(0).getAsJsonObject();
            System.out.println("First result: " + first.get("title").getAsString() + " (search near " + location + ")");
        } catch (SerpApiException e) {
            System.out.println("SerpApi request failed.");
            e.printStackTrace();
            System.exit(1);
        }
    }
}
